name: Continuous deployment

on: push

jobs:
  continuous-deployment:
    name: Run tests and publish documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup OCaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.11.1

      - run: opam pin add delimcc git+https://github.com/GauBen/delimcc

      - run: opam pin . --no-action

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- dune runtest

      - run: opam exec -- dune build @doc

      - name: Publish documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/default/_doc/_html
          publish_branch: docs
